server:
  port: 8080

springbootwebfluxjjwt:
  jjwt:
    secret: ThisIsSecretForJWTHS512SignatureAlgorithmThatMUSTHave64ByteLength
    expiration: 28800

spring:
  application:
    name: authentication-service

  redis:
    database: 5
    host: localhost
    port: 6379

  jpa:
    hibernate:
      ddl-auto: none

  datasource:
    url: jdbc:mysql://localhost:3307/justmop
    username: root
    password: root

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
eureka:
  client:
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8083/eureka